name: Default branch

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create mongoDB Docker container for API testing
        uses: DigiPie/mongo-action@v1.0.1
      - name: Test mongo connection
        id: test_mongo_connection
        run: 'sudo mongo localhost:27017'
      - run: cd server && npm ci
      - run: npm test
        env:
          CI: true
          DB_URI: mongodb://localhost:27017
          DB_NAME: ci-test-database
