name: feature/bugfix branch

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install mongosh
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh
      - name: Create mongo Docker container
        uses: DigiPie/mongo-action@v2.0.1
        with:
          image_version: latest
          port: 27017
      - name: Test mongo connection
        run: 'sudo mongosh localhost:27017'
      - run: cd server && npm i
      - run: cd frontend && npm i
      - run: npm test
        env:
          CI: true
          INGEGRATION_TEST_DB_URI: mongodb://localhost:27017/ci-test-database

  test-e2e-cypress:
    needs: test
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install mongosh
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh
      - name: Create mongo Docker container
        uses: DigiPie/mongo-action@v2.0.0
        with:
          image_version: latest
          port: 27017
      - name: Test mongo connection
        run: 'sudo mongosh localhost:27017'
      - run: npm install
      - run: npm run build-ci
      - run: npm run start-server-for-e2e
        env:
          NODE_ENV: production
          DB_URI: mongodb://localhost:27017/e2e-test-database
          CI: true
      - run: cd e2e && npm run test:ci
        env:
          E2E_BASE_URL: http://localhost:5001
