name: feature/bugfix branch

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create mongoDB Docker container for API testing
        uses: DigiPie/mongo-action@v1.0.1
      - name: Test mongo connection
        id: test_mongo_connection
        run: 'sudo mongo localhost:27017'
      - run: cd server && npm i
      - run: cd frontend && npm i
      - run: npm test
        env:
          CI: true
          INGEGRATION_TEST_DB_URI: mongodb://localhost:27017/ci-test-database

  test-e2e-wdio:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install WDIO e2e dependencies
        run: cd e2e-wdio && npm install
      - name: Run WDIO e2e tests on DEV environement
        run: cd e2e-wdio && npm run test:ci -- --baseUrl http://social-community-app-dev.herokuapp.com
      # TODO - figure out what is going on with logs directory (?)
      # - uses: actions/upload-artifact@v1
      #   if: failure()
      #   with:
      #     name: logs
      #     path: logs
      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: e2e-wdio/allure-results
          gh_pages: feature-allure-report
          allure_report: allure-report
          allure_history: allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: feature-allure-report
          PUBLISH_DIR: allure-history
      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: https://mdziadkowiec95.github.io/social-community-app/${{ github.run_number }}

  test-e2e-cypress:
    needs: test
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create mongoDB Docker container for API testing
        uses: DigiPie/mongo-action@v1.0.1
      - name: Test mongo connection
        id: test_mongo_connection
        run: 'sudo mongo localhost:27017'
      - run: npm install
      - run: npm run build-ci
      - run: npm run start-server-for-e2e
        env:
          NODE_ENV: production
          DB_URI: mongodb://localhost:27017/e2e-test-database
          CI: true
      - run: cd e2e && npm run test:ci
        env:
          E2E_BASE_URL: http://localhost:5001
